package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.*;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "actors", schema = "public")
public class Actor implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "actorid", unique = true, nullable = false)
    private Integer actorid;

    @Column(name = "name", nullable = false, length = 250)
    private String name;

    @Column(name = "sex", length = 1)
    private Character sex;

    public Actor() {
    }

    public Actor(Integer actorid, String name) {
        this.actorid = actorid;
        this.name = name;
    }

    public Actor(Integer actorid, String name, Character sex) {
        this.actorid = actorid;
        this.name = name;
        this.sex = sex;
    }


    public Integer getActorid() {
        return this.actorid;
    }

    public void setActorid(Integer actorid) {
        this.actorid = actorid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Actor actor = (Actor) o;

        if (actorid != null ? !actorid.equals(actor.actorid) : actor.actorid != null) return false;
        if (name != null ? !name.equals(actor.name) : actor.name != null) return false;
        if (sex != null ? !sex.equals(actor.sex) : actor.sex != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = actorid != null ? actorid.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (sex != null ? sex.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
                .append("actorid", actorid)
                .append("name", name)
                .append("sex", sex)
                .toString();
    }
}
