package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AkanamesId generated by hbm2java
 */
@Embeddable
public class AkanamesId implements java.io.Serializable {

    private String name;
    private String akaname;
    private String addition;

    public AkanamesId() {
    }

    public AkanamesId(String name, String akaname) {
        this.name = name;
        this.akaname = akaname;
    }

    public AkanamesId(String name, String akaname, String addition) {
        this.name = name;
        this.akaname = akaname;
        this.addition = addition;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "akaname", nullable = false, length = 250)
    public String getAkaname() {
        return this.akaname;
    }

    public void setAkaname(String akaname) {
        this.akaname = akaname;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AkanamesId))
            return false;
        AkanamesId castOther = (AkanamesId) other;

        return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
                .getName()
                .equals(castOther.getName())))
                && ((this.getAkaname() == castOther.getAkaname()) || (this.getAkaname() != null
                && castOther.getAkaname() != null && this.getAkaname().equals(castOther.getAkaname())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getAkaname() == null ? 0 : this.getAkaname().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
