package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Akanames generated by hbm2java
 */
@Entity
@Table(name = "akanames", schema = "public")
public class Akanames implements java.io.Serializable {

    private AkanamesId id;

    public Akanames() {
    }

    public Akanames(AkanamesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 250)),
            @AttributeOverride(name = "akaname", column = @Column(name = "akaname", nullable = false, length = 250)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public AkanamesId getId() {
        return this.id;
    }

    public void setId(AkanamesId id) {
        this.id = id;
    }

}
