package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Akatitles generated by hbm2java
 */
@Entity
@Table(name = "akatitles", schema = "public")
public class Akatitles implements java.io.Serializable {

    private AkatitlesId id;

    public Akatitles() {
    }

    public Akatitles(AkatitlesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "language", column = @Column(name = "language", nullable = false, length = 3)),
            @AttributeOverride(name = "title", column = @Column(name = "title", nullable = false, length = 400)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public AkatitlesId getId() {
        return this.id;
    }

    public void setId(AkatitlesId id) {
        this.id = id;
    }

}
