package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AkatitlesId generated by hbm2java
 */
@Embeddable
public class AkatitlesId implements java.io.Serializable {

    private int movieid;
    private String language;
    private String title;
    private String addition;

    public AkatitlesId() {
    }

    public AkatitlesId(int movieid, String language, String title) {
        this.movieid = movieid;
        this.language = language;
        this.title = title;
    }

    public AkatitlesId(int movieid, String language, String title, String addition) {
        this.movieid = movieid;
        this.language = language;
        this.title = title;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "language", nullable = false, length = 3)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "title", nullable = false, length = 400)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AkatitlesId))
            return false;
        AkatitlesId castOther = (AkatitlesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
                && castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
                && ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
                && castOther.getTitle() != null && this.getTitle().equals(castOther.getTitle())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
        result = 37 * result + (getTitle() == null ? 0 : this.getTitle().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
