package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AltversionsId generated by hbm2java
 */
@Embeddable
public class AltversionsId implements java.io.Serializable {

    private int movieid;
    private String versiontext;

    public AltversionsId() {
    }

    public AltversionsId(int movieid) {
        this.movieid = movieid;
    }

    public AltversionsId(int movieid, String versiontext) {
        this.movieid = movieid;
        this.versiontext = versiontext;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "versiontext")
    public String getVersiontext() {
        return this.versiontext;
    }

    public void setVersiontext(String versiontext) {
        this.versiontext = versiontext;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof AltversionsId))
            return false;
        AltversionsId castOther = (AltversionsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getVersiontext() == castOther.getVersiontext()) || (this.getVersiontext() != null
                && castOther.getVersiontext() != null && this
                .getVersiontext()
                .equals(castOther.getVersiontext())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getVersiontext() == null ? 0 : this.getVersiontext().hashCode());
        return result;
    }

}
