package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Altversions generated by hbm2java
 */
@Entity
@Table(name = "altversions", schema = "public")
public class Altversions implements java.io.Serializable {

    private AltversionsId id;

    public Altversions() {
    }

    public Altversions(AltversionsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "versiontext", column = @Column(name = "versiontext"))})
    public AltversionsId getId() {
        return this.id;
    }

    public void setId(AltversionsId id) {
        this.id = id;
    }

}
