package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Business generated by hbm2java
 */
@Entity
@Table(name = "business", schema = "public")
public class Business implements java.io.Serializable {

    private int movieid;
    private String businesstext;

    public Business() {
    }

    public Business(int movieid) {
        this.movieid = movieid;
    }

    public Business(int movieid, String businesstext) {
        this.movieid = movieid;
        this.businesstext = businesstext;
    }

    @Id
    @Column(name = "movieid", unique = true, nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "businesstext")
    public String getBusinesstext() {
        return this.businesstext;
    }

    public void setBusinesstext(String businesstext) {
        this.businesstext = businesstext;
    }

}
