package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CertificatesId generated by hbm2java
 */
@Embeddable
public class CertificatesId implements java.io.Serializable {

    private int movieid;
    private String country;
    private String certification;
    private String addition;

    public CertificatesId() {
    }

    public CertificatesId(int movieid, String certification) {
        this.movieid = movieid;
        this.certification = certification;
    }

    public CertificatesId(int movieid, String country, String certification, String addition) {
        this.movieid = movieid;
        this.country = country;
        this.certification = certification;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "country", length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "certification", nullable = false)
    public String getCertification() {
        return this.certification;
    }

    public void setCertification(String certification) {
        this.certification = certification;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof CertificatesId))
            return false;
        CertificatesId castOther = (CertificatesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
                && castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
                && ((this.getCertification() == castOther.getCertification()) || (this.getCertification() != null
                && castOther.getCertification() != null && this
                .getCertification()
                .equals(castOther.getCertification())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
        result = 37 * result + (getCertification() == null ? 0 : this.getCertification().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
