package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Certificates generated by hbm2java
 */
@Entity
@Table(name = "certificates", schema = "public")
public class Certificates implements java.io.Serializable {

    private CertificatesId id;

    public Certificates() {
    }

    public Certificates(CertificatesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "country", column = @Column(name = "country", length = 50)),
            @AttributeOverride(name = "certification", column = @Column(name = "certification", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public CertificatesId getId() {
        return this.id;
    }

    public void setId(CertificatesId id) {
        this.id = id;
    }

}
