package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cinematgrs generated by hbm2java
 */
@Entity
@Table(name = "cinematgrs", schema = "public")
public class Cinematgrs implements java.io.Serializable {

    private int cinematid;
    private String name;

    public Cinematgrs() {
    }

    public Cinematgrs(int cinematid, String name) {
        this.cinematid = cinematid;
        this.name = name;
    }

    @Id
    @Column(name = "cinematid", unique = true, nullable = false)
    public int getCinematid() {
        return this.cinematid;
    }

    public void setCinematid(int cinematid) {
        this.cinematid = cinematid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
