package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Colorinfo generated by hbm2java
 */
@Entity
@Table(name = "colorinfo", schema = "public")
public class Colorinfo implements java.io.Serializable {

    private ColorinfoId id;

    public Colorinfo() {
    }

    public Colorinfo(ColorinfoId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "color", column = @Column(name = "color", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition"))})
    public ColorinfoId getId() {
        return this.id;
    }

    public void setId(ColorinfoId id) {
        this.id = id;
    }

}
