package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Costdesigners generated by hbm2java
 */
@Entity
@Table(name = "costdesigners", schema = "public")
public class Costdesigners implements java.io.Serializable {

    private int costdesid;
    private String name;

    public Costdesigners() {
    }

    public Costdesigners(int costdesid, String name) {
        this.costdesid = costdesid;
        this.name = name;
    }

    @Id
    @Column(name = "costdesid", unique = true, nullable = false)
    public int getCostdesid() {
        return this.costdesid;
    }

    public void setCostdesid(int costdesid) {
        this.costdesid = costdesid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
