package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", schema = "public")
public class Countries implements java.io.Serializable {

    private CountriesId id;

    public Countries() {
    }

    public Countries(CountriesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "country", column = @Column(name = "country", nullable = false, length = 50))})
    public CountriesId getId() {
        return this.id;
    }

    public void setId(CountriesId id) {
        this.id = id;
    }

}
