package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Crazycredits generated by hbm2java
 */
@Entity
@Table(name = "crazycredits", schema = "public")
public class Crazycredits implements java.io.Serializable {

    private CrazycreditsId id;

    public Crazycredits() {
    }

    public Crazycredits(CrazycreditsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "credittext", column = @Column(name = "credittext"))})
    public CrazycreditsId getId() {
        return this.id;
    }

    public void setId(CrazycreditsId id) {
        this.id = id;
    }

}
