package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Directors generated by hbm2java
 */
@Entity
@Table(name = "directors", schema = "public")
public class Directors implements java.io.Serializable {

    private int directorid;
    private String name;

    public Directors() {
    }

    public Directors(int directorid, String name) {
        this.directorid = directorid;
        this.name = name;
    }

    @Id
    @Column(name = "directorid", unique = true, nullable = false)
    public int getDirectorid() {
        return this.directorid;
    }

    public void setDirectorid(int directorid) {
        this.directorid = directorid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
