package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Distributors generated by hbm2java
 */
@Entity
@Table(name = "distributors", schema = "public")
public class Distributors implements java.io.Serializable {

    private DistributorsId id;

    public Distributors() {
    }

    public Distributors(DistributorsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 250)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public DistributorsId getId() {
        return this.id;
    }

    public void setId(DistributorsId id) {
        this.id = id;
    }

}
