package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Editors generated by hbm2java
 */
@Entity
@Table(name = "editors", schema = "public")
public class Editors implements java.io.Serializable {

    private int editorid;
    private String name;

    public Editors() {
    }

    public Editors(int editorid, String name) {
        this.editorid = editorid;
        this.name = name;
    }

    @Id
    @Column(name = "editorid", unique = true, nullable = false)
    public int getEditorid() {
        return this.editorid;
    }

    public void setEditorid(int editorid) {
        this.editorid = editorid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
