package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "genres", schema = "public")
public class Genres implements java.io.Serializable {

    private GenresId id;

    public Genres() {
    }

    public Genres(GenresId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "genre", column = @Column(name = "genre", nullable = false, length = 50))})
    public GenresId getId() {
        return this.id;
    }

    public void setId(GenresId id) {
        this.id = id;
    }

}
