package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KeywordsId generated by hbm2java
 */
@Embeddable
public class KeywordsId implements java.io.Serializable {

    private int movieid;
    private String keyword;

    public KeywordsId() {
    }

    public KeywordsId(int movieid, String keyword) {
        this.movieid = movieid;
        this.keyword = keyword;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "keyword", nullable = false)
    public String getKeyword() {
        return this.keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof KeywordsId))
            return false;
        KeywordsId castOther = (KeywordsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getKeyword() == castOther.getKeyword()) || (this.getKeyword() != null
                && castOther.getKeyword() != null && this.getKeyword().equals(castOther.getKeyword())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getKeyword() == null ? 0 : this.getKeyword().hashCode());
        return result;
    }

}
