package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Keywords generated by hbm2java
 */
@Entity
@Table(name = "keywords", schema = "public")
public class Keywords implements java.io.Serializable {

    private KeywordsId id;

    public Keywords() {
    }

    public Keywords(KeywordsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "keyword", column = @Column(name = "keyword", nullable = false))})
    public KeywordsId getId() {
        return this.id;
    }

    public void setId(KeywordsId id) {
        this.id = id;
    }

}
