package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LanguageId generated by hbm2java
 */
@Embeddable
public class LanguageId implements java.io.Serializable {

    private int movieid;
    private String language;
    private String addition;

    public LanguageId() {
    }

    public LanguageId(int movieid, String language) {
        this.movieid = movieid;
        this.language = language;
    }

    public LanguageId(int movieid, String language, String addition) {
        this.movieid = movieid;
        this.language = language;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "language", nullable = false, length = 100)
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof LanguageId))
            return false;
        LanguageId castOther = (LanguageId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
                && castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
