package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language", schema = "public")
public class Language implements java.io.Serializable {

    private LanguageId id;

    public Language() {
    }

    public Language(LanguageId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "language", column = @Column(name = "language", nullable = false, length = 100)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public LanguageId getId() {
        return this.id;
    }

    public void setId(LanguageId id) {
        this.id = id;
    }

}
