package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LiteratureId generated by hbm2java
 */
@Embeddable
public class LiteratureId implements java.io.Serializable {

    private int movieid;
    private String literaturetext;

    public LiteratureId() {
    }

    public LiteratureId(int movieid) {
        this.movieid = movieid;
    }

    public LiteratureId(int movieid, String literaturetext) {
        this.movieid = movieid;
        this.literaturetext = literaturetext;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "literaturetext")
    public String getLiteraturetext() {
        return this.literaturetext;
    }

    public void setLiteraturetext(String literaturetext) {
        this.literaturetext = literaturetext;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof LiteratureId))
            return false;
        LiteratureId castOther = (LiteratureId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getLiteraturetext() == castOther.getLiteraturetext()) || (this.getLiteraturetext() != null
                && castOther.getLiteraturetext() != null && this
                .getLiteraturetext()
                .equals(castOther.getLiteraturetext())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getLiteraturetext() == null ? 0 : this.getLiteraturetext().hashCode());
        return result;
    }

}
