package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocationsId generated by hbm2java
 */
@Embeddable
public class LocationsId implements java.io.Serializable {

    private int movieid;
    private String location;
    private String addition;

    public LocationsId() {
    }

    public LocationsId(int movieid, String location) {
        this.movieid = movieid;
        this.location = location;
    }

    public LocationsId(int movieid, String location, String addition) {
        this.movieid = movieid;
        this.location = location;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "location", nullable = false, length = 1000)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof LocationsId))
            return false;
        LocationsId castOther = (LocationsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getLocation() == castOther.getLocation()) || (this.getLocation() != null
                && castOther.getLocation() != null && this.getLocation().equals(castOther.getLocation())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getLocation() == null ? 0 : this.getLocation().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
