package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "locations", schema = "public")
public class Locations implements java.io.Serializable {

    private LocationsId id;

    public Locations() {
    }

    public Locations(LocationsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "location", column = @Column(name = "location", nullable = false, length = 1000)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public LocationsId getId() {
        return this.id;
    }

    public void setId(LocationsId id) {
        this.id = id;
    }

}
