package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Misc generated by hbm2java
 */
@Entity
@Table(name = "misc", schema = "public")
public class Misc implements java.io.Serializable {

    private int miscid;
    private String name;

    public Misc() {
    }

    public Misc(int miscid, String name) {
        this.miscid = miscid;
        this.name = name;
    }

    @Id
    @Column(name = "miscid", unique = true, nullable = false)
    public int getMiscid() {
        return this.miscid;
    }

    public void setMiscid(int miscid) {
        this.miscid = miscid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
