package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2editorsId generated by hbm2java
 */
@Embeddable
public class Movies2editorsId implements java.io.Serializable {

    private int movieid;
    private int editorid;
    private String addition;

    public Movies2editorsId() {
    }

    public Movies2editorsId(int movieid, int editorid) {
        this.movieid = movieid;
        this.editorid = editorid;
    }

    public Movies2editorsId(int movieid, int editorid, String addition) {
        this.movieid = movieid;
        this.editorid = editorid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "editorid", nullable = false)
    public int getEditorid() {
        return this.editorid;
    }

    public void setEditorid(int editorid) {
        this.editorid = editorid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2editorsId))
            return false;
        Movies2editorsId castOther = (Movies2editorsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getEditorid() == castOther.getEditorid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getEditorid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
