package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movielinks generated by hbm2java
 */
@Entity
@Table(name = "movielinks", schema = "public")
public class Movielinks implements java.io.Serializable {

    private MovielinksId id;

    public Movielinks() {
    }

    public Movielinks(MovielinksId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "movielinkstext", column = @Column(name = "movielinkstext"))})
    public MovielinksId getId() {
        return this.id;
    }

    public void setId(MovielinksId id) {
        this.id = id;
    }

}
