package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2cinematgrsId generated by hbm2java
 */
@Embeddable
public class Movies2cinematgrsId implements java.io.Serializable {

    private int movieid;
    private int cinematid;
    private String addition;

    public Movies2cinematgrsId() {
    }

    public Movies2cinematgrsId(int movieid, int cinematid) {
        this.movieid = movieid;
        this.cinematid = cinematid;
    }

    public Movies2cinematgrsId(int movieid, int cinematid, String addition) {
        this.movieid = movieid;
        this.cinematid = cinematid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "cinematid", nullable = false)
    public int getCinematid() {
        return this.cinematid;
    }

    public void setCinematid(int cinematid) {
        this.cinematid = cinematid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2cinematgrsId))
            return false;
        Movies2cinematgrsId castOther = (Movies2cinematgrsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getCinematid() == castOther.getCinematid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getCinematid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
