package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2misc generated by hbm2java
 */
@Entity
@Table(name = "movies2misc", schema = "public")
public class Movies2misc implements java.io.Serializable {

    private Movies2miscId id;

    public Movies2misc() {
    }

    public Movies2misc(Movies2miscId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "miscid", column = @Column(name = "miscid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2miscId getId() {
        return this.id;
    }

    public void setId(Movies2miscId id) {
        this.id = id;
    }

}
