package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2miscId generated by hbm2java
 */
@Embeddable
public class Movies2miscId implements java.io.Serializable {

    private int movieid;
    private int miscid;
    private String addition;

    public Movies2miscId() {
    }

    public Movies2miscId(int movieid, int miscid) {
        this.movieid = movieid;
        this.miscid = miscid;
    }

    public Movies2miscId(int movieid, int miscid, String addition) {
        this.movieid = movieid;
        this.miscid = miscid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "miscid", nullable = false)
    public int getMiscid() {
        return this.miscid;
    }

    public void setMiscid(int miscid) {
        this.miscid = miscid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2miscId))
            return false;
        Movies2miscId castOther = (Movies2miscId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getMiscid() == castOther.getMiscid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getMiscid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
