package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2composersId generated by hbm2java
 */
@Embeddable
public class Movies2composersId implements java.io.Serializable {

    private int movieid;
    private int composerid;
    private String addition;

    public Movies2composersId() {
    }

    public Movies2composersId(int movieid, int composerid) {
        this.movieid = movieid;
        this.composerid = composerid;
    }

    public Movies2composersId(int movieid, int composerid, String addition) {
        this.movieid = movieid;
        this.composerid = composerid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "composerid", nullable = false)
    public int getComposerid() {
        return this.composerid;
    }

    public void setComposerid(int composerid) {
        this.composerid = composerid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2composersId))
            return false;
        Movies2composersId castOther = (Movies2composersId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getComposerid() == castOther.getComposerid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getComposerid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
