package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2proddesId generated by hbm2java
 */
@Embeddable
public class Movies2proddesId implements java.io.Serializable {

    private int movieid;
    private int proddesid;
    private String addition;

    public Movies2proddesId() {
    }

    public Movies2proddesId(int movieid, int proddesid) {
        this.movieid = movieid;
        this.proddesid = proddesid;
    }

    public Movies2proddesId(int movieid, int proddesid, String addition) {
        this.movieid = movieid;
        this.proddesid = proddesid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "proddesid", nullable = false)
    public int getProddesid() {
        return this.proddesid;
    }

    public void setProddesid(int proddesid) {
        this.proddesid = proddesid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2proddesId))
            return false;
        Movies2proddesId castOther = (Movies2proddesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getProddesid() == castOther.getProddesid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getProddesid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
