package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2writers generated by hbm2java
 */
@Entity
@Table(name = "movies2writers", schema = "public")
public class Movies2writers implements java.io.Serializable {

    private Movies2writersId id;

    public Movies2writers() {
    }

    public Movies2writers(Movies2writersId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "writerid", column = @Column(name = "writerid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2writersId getId() {
        return this.id;
    }

    public void setId(Movies2writersId id) {
        this.id = id;
    }

}
