package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2proddes generated by hbm2java
 */
@Entity
@Table(name = "movies2proddes", schema = "public")
public class Movies2proddes implements java.io.Serializable {

    private Movies2proddesId id;

    public Movies2proddes() {
    }

    public Movies2proddes(Movies2proddesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "proddesid", column = @Column(name = "proddesid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2proddesId getId() {
        return this.id;
    }

    public void setId(Movies2proddesId id) {
        this.id = id;
    }

}
