package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2composers generated by hbm2java
 */
@Entity
@Table(name = "movies2composers", schema = "public")
public class Movies2composers implements java.io.Serializable {

    private Movies2composersId id;

    public Movies2composers() {
    }

    public Movies2composers(Movies2composersId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "composerid", column = @Column(name = "composerid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2composersId getId() {
        return this.id;
    }

    public void setId(Movies2composersId id) {
        this.id = id;
    }

}
