package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2costdes generated by hbm2java
 */
@Entity
@Table(name = "movies2costdes", schema = "public")
public class Movies2costdes implements java.io.Serializable {

    private Movies2costdesId id;

    public Movies2costdes() {
    }

    public Movies2costdes(Movies2costdesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "costdesid", column = @Column(name = "costdesid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2costdesId getId() {
        return this.id;
    }

    public void setId(Movies2costdesId id) {
        this.id = id;
    }

}
