package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Movies2costdesId generated by hbm2java
 */
@Embeddable
public class Movies2costdesId implements java.io.Serializable {

    private int movieid;
    private int costdesid;
    private String addition;

    public Movies2costdesId() {
    }

    public Movies2costdesId(int movieid, int costdesid) {
        this.movieid = movieid;
        this.costdesid = costdesid;
    }

    public Movies2costdesId(int movieid, int costdesid, String addition) {
        this.movieid = movieid;
        this.costdesid = costdesid;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "costdesid", nullable = false)
    public int getCostdesid() {
        return this.costdesid;
    }

    public void setCostdesid(int costdesid) {
        this.costdesid = costdesid;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof Movies2costdesId))
            return false;
        Movies2costdesId castOther = (Movies2costdesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && (this.getCostdesid() == castOther.getCostdesid())
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + this.getCostdesid();
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
