package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Movies2producers generated by hbm2java
 */
@Entity
@Table(name = "movies2producers", schema = "public")
public class Movies2producers implements java.io.Serializable {

    private Movies2producersId id;

    public Movies2producers() {
    }

    public Movies2producers(Movies2producersId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "producerid", column = @Column(name = "producerid", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public Movies2producersId getId() {
        return this.id;
    }

    public void setId(Movies2producersId id) {
        this.id = id;
    }

}
