package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Mpaaratings generated by hbm2java
 */
@Entity
@Table(name = "mpaaratings", schema = "public")
public class Mpaaratings implements java.io.Serializable {

    private MpaaratingsId id;

    public Mpaaratings() {
    }

    public Mpaaratings(MpaaratingsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "reasontext", column = @Column(name = "reasontext"))})
    public MpaaratingsId getId() {
        return this.id;
    }

    public void setId(MpaaratingsId id) {
        this.id = id;
    }

}
