package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MpaaratingsId generated by hbm2java
 */
@Embeddable
public class MpaaratingsId implements java.io.Serializable {

    private int movieid;
    private String reasontext;

    public MpaaratingsId() {
    }

    public MpaaratingsId(int movieid) {
        this.movieid = movieid;
    }

    public MpaaratingsId(int movieid, String reasontext) {
        this.movieid = movieid;
        this.reasontext = reasontext;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "reasontext")
    public String getReasontext() {
        return this.reasontext;
    }

    public void setReasontext(String reasontext) {
        this.reasontext = reasontext;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof MpaaratingsId))
            return false;
        MpaaratingsId castOther = (MpaaratingsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getReasontext() == castOther.getReasontext()) || (this.getReasontext() != null
                && castOther.getReasontext() != null && this.getReasontext().equals(castOther.getReasontext())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getReasontext() == null ? 0 : this.getReasontext().hashCode());
        return result;
    }

}
