package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Plots generated by hbm2java
 */
@Entity
@Table(name = "plots", schema = "public")
public class Plots implements java.io.Serializable {

    private PlotsId id;

    public Plots() {
    }

    public Plots(PlotsId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "plottext", column = @Column(name = "plottext"))})
    public PlotsId getId() {
        return this.id;
    }

    public void setId(PlotsId id) {
        this.id = id;
    }

}
