package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proddesigners generated by hbm2java
 */
@Entity
@Table(name = "proddesigners", schema = "public")
public class Proddesigners implements java.io.Serializable {

    private int proddesid;
    private String name;

    public Proddesigners() {
    }

    public Proddesigners(int proddesid, String name) {
        this.proddesid = proddesid;
        this.name = name;
    }

    @Id
    @Column(name = "proddesid", unique = true, nullable = false)
    public int getProddesid() {
        return this.proddesid;
    }

    public void setProddesid(int proddesid) {
        this.proddesid = proddesid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
