package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RatingsId generated by hbm2java
 */
@Embeddable
public class RatingsId implements java.io.Serializable {

    private int movieid;
    private String rank;
    private Integer votes;
    private String distribution;

    public RatingsId() {
    }

    public RatingsId(int movieid, String rank, String distribution) {
        this.movieid = movieid;
        this.rank = rank;
        this.distribution = distribution;
    }

    public RatingsId(int movieid, String rank, Integer votes, String distribution) {
        this.movieid = movieid;
        this.rank = rank;
        this.votes = votes;
        this.distribution = distribution;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "rank", nullable = false, length = 4)
    public String getRank() {
        return this.rank;
    }

    public void setRank(String rank) {
        this.rank = rank;
    }

    @Column(name = "votes")
    public Integer getVotes() {
        return this.votes;
    }

    public void setVotes(Integer votes) {
        this.votes = votes;
    }

    @Column(name = "distribution", nullable = false, length = 10)
    public String getDistribution() {
        return this.distribution;
    }

    public void setDistribution(String distribution) {
        this.distribution = distribution;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RatingsId))
            return false;
        RatingsId castOther = (RatingsId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getRank() == castOther.getRank()) || (this.getRank() != null && castOther.getRank() != null && this
                .getRank()
                .equals(castOther.getRank())))
                && ((this.getVotes() == castOther.getVotes()) || (this.getVotes() != null
                && castOther.getVotes() != null && this.getVotes().equals(castOther.getVotes())))
                && ((this.getDistribution() == castOther.getDistribution()) || (this.getDistribution() != null
                && castOther.getDistribution() != null && this
                .getDistribution()
                .equals(castOther.getDistribution())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getRank() == null ? 0 : this.getRank().hashCode());
        result = 37 * result + (getVotes() == null ? 0 : this.getVotes().hashCode());
        result = 37 * result + (getDistribution() == null ? 0 : this.getDistribution().hashCode());
        return result;
    }

}
