package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Releasedates generated by hbm2java
 */
@Entity
@Table(name = "releasedates", schema = "public")
public class Releasedates implements java.io.Serializable {

    private ReleasedatesId id;

    public Releasedates() {
    }

    public Releasedates(ReleasedatesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "country", column = @Column(name = "country", length = 50)),
            @AttributeOverride(name = "imdbdate", column = @Column(name = "imdbdate", nullable = false, length = 50)),
            @AttributeOverride(name = "releasedate", column = @Column(name = "releasedate", length = 13)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", length = 1000))})
    public ReleasedatesId getId() {
        return this.id;
    }

    public void setId(ReleasedatesId id) {
        this.id = id;
    }

}
