package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * ReleasedatesId generated by hbm2java
 */
@Embeddable
public class ReleasedatesId implements java.io.Serializable {

    private int movieid;
    private String country;
    private String imdbdate;
    private Date releasedate;
    private String addition;

    public ReleasedatesId() {
    }

    public ReleasedatesId(int movieid, String imdbdate) {
        this.movieid = movieid;
        this.imdbdate = imdbdate;
    }

    public ReleasedatesId(int movieid, String country, String imdbdate, Date releasedate, String addition) {
        this.movieid = movieid;
        this.country = country;
        this.imdbdate = imdbdate;
        this.releasedate = releasedate;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "country", length = 50)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "imdbdate", nullable = false, length = 50)
    public String getImdbdate() {
        return this.imdbdate;
    }

    public void setImdbdate(String imdbdate) {
        this.imdbdate = imdbdate;
    }

    @Column(name = "releasedate", length = 13)
    public Date getReleasedate() {
        return this.releasedate;
    }

    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ReleasedatesId))
            return false;
        ReleasedatesId castOther = (ReleasedatesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
                && castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
                && ((this.getImdbdate() == castOther.getImdbdate()) || (this.getImdbdate() != null
                && castOther.getImdbdate() != null && this.getImdbdate().equals(castOther.getImdbdate())))
                && ((this.getReleasedate() == castOther.getReleasedate()) || (this.getReleasedate() != null
                && castOther.getReleasedate() != null && this
                .getReleasedate()
                .equals(castOther.getReleasedate())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
        result = 37 * result + (getImdbdate() == null ? 0 : this.getImdbdate().hashCode());
        result = 37 * result + (getReleasedate() == null ? 0 : this.getReleasedate().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
