package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RunningtimesId generated by hbm2java
 */
@Embeddable
public class RunningtimesId implements java.io.Serializable {

    private int movieid;
    private String time;
    private String addition;

    public RunningtimesId() {
    }

    public RunningtimesId(int movieid, String time, String addition) {
        this.movieid = movieid;
        this.time = time;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "time", nullable = false, length = 50)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Column(name = "addition", nullable = false, length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RunningtimesId))
            return false;
        RunningtimesId castOther = (RunningtimesId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null && this
                .getTime()
                .equals(castOther.getTime())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
