package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Runningtimes generated by hbm2java
 */
@Entity
@Table(name = "runningtimes", schema = "public")
public class Runningtimes implements java.io.Serializable {

    private RunningtimesId id;

    public Runningtimes() {
    }

    public Runningtimes(RunningtimesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "time", column = @Column(name = "time", nullable = false, length = 50)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition", nullable = false, length = 1000))})
    public RunningtimesId getId() {
        return this.id;
    }

    public void setId(RunningtimesId id) {
        this.id = id;
    }

}
