package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Soundmix generated by hbm2java
 */
@Entity
@Table(name = "soundmix", schema = "public")
public class Soundmix implements java.io.Serializable {

    private SoundmixId id;

    public Soundmix() {
    }

    public Soundmix(SoundmixId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "sound", column = @Column(name = "sound", nullable = false)),
            @AttributeOverride(name = "addition", column = @Column(name = "addition"))})
    public SoundmixId getId() {
        return this.id;
    }

    public void setId(SoundmixId id) {
        this.id = id;
    }

}
