package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Soundtracks generated by hbm2java
 */
@Entity
@Table(name = "soundtracks", schema = "public")
public class Soundtracks implements java.io.Serializable {

    private SoundtracksId id;

    public Soundtracks() {
    }

    public Soundtracks(SoundtracksId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "soundtracktext", column = @Column(name = "soundtracktext"))})
    public SoundtracksId getId() {
        return this.id;
    }

    public void setId(SoundtracksId id) {
        this.id = id;
    }

}
