package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Taglines generated by hbm2java
 */
@Entity
@Table(name = "taglines", schema = "public")
public class Taglines implements java.io.Serializable {

    private TaglinesId id;

    public Taglines() {
    }

    public Taglines(TaglinesId id) {
        this.id = id;
    }

    @EmbeddedId
    @AttributeOverrides({@AttributeOverride(name = "movieid", column = @Column(name = "movieid", nullable = false)),
            @AttributeOverride(name = "taglinetext", column = @Column(name = "taglinetext"))})
    public TaglinesId getId() {
        return this.id;
    }

    public void setId(TaglinesId id) {
        this.id = id;
    }

}
