package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TechnicalId generated by hbm2java
 */
@Embeddable
public class TechnicalId implements java.io.Serializable {

    private int movieid;
    private String name;
    private String addition;

    public TechnicalId() {
    }

    public TechnicalId(int movieid, String name) {
        this.movieid = movieid;
        this.name = name;
    }

    public TechnicalId(int movieid, String name, String addition) {
        this.movieid = movieid;
        this.name = name;
        this.addition = addition;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "name", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "addition", length = 1000)
    public String getAddition() {
        return this.addition;
    }

    public void setAddition(String addition) {
        this.addition = addition;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TechnicalId))
            return false;
        TechnicalId castOther = (TechnicalId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null && this
                .getName()
                .equals(castOther.getName())))
                && ((this.getAddition() == castOther.getAddition()) || (this.getAddition() != null
                && castOther.getAddition() != null && this.getAddition().equals(castOther.getAddition())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
        result = 37 * result + (getAddition() == null ? 0 : this.getAddition().hashCode());
        return result;
    }

}
