package liquibasedemo.data;

// Generated 2015-05-04 22:44:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TriviaId generated by hbm2java
 */
@Embeddable
public class TriviaId implements java.io.Serializable {

    private int movieid;
    private String triviatext;

    public TriviaId() {
    }

    public TriviaId(int movieid) {
        this.movieid = movieid;
    }

    public TriviaId(int movieid, String triviatext) {
        this.movieid = movieid;
        this.triviatext = triviatext;
    }

    @Column(name = "movieid", nullable = false)
    public int getMovieid() {
        return this.movieid;
    }

    public void setMovieid(int movieid) {
        this.movieid = movieid;
    }

    @Column(name = "triviatext")
    public String getTriviatext() {
        return this.triviatext;
    }

    public void setTriviatext(String triviatext) {
        this.triviatext = triviatext;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TriviaId))
            return false;
        TriviaId castOther = (TriviaId) other;

        return (this.getMovieid() == castOther.getMovieid())
                && ((this.getTriviatext() == castOther.getTriviatext()) || (this.getTriviatext() != null
                && castOther.getTriviatext() != null && this.getTriviatext().equals(castOther.getTriviatext())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getMovieid();
        result = 37 * result + (getTriviatext() == null ? 0 : this.getTriviatext().hashCode());
        return result;
    }

}
